#!/usr/bin/env python3
"""Deterministic whole-corpus skill integrity audit.

Builds on ``tools.check_skill_quality`` and adds orthogonal integrity findings
that the quality tiers intentionally do not model: duplicate titles or
content, stale version metadata, broken related-skill links, and syntax errors
in fenced Python examples.

The audit is conservative. It never invents freshness or compatibility facts;
``stale`` is reported only when the declared version contradicts the skill's
own changelog (for example, ``version: v1`` while the changelog documents v2).
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path

from tools.check_skill_quality import (
    REPO_ROOT,
    _description_value,
    classify,
    iter_skill_files,
    parse_frontmatter,
)

AUDIT_PATH = REPO_ROOT / "meta" / "SKILL-CORPUS-AUDIT.md"
RELATED_RE = re.compile(r"(?:^|\n)-\s+(?:`([^`]+\.md)`|\[[^\]]+\]\(([^)]+\.md)\))", re.MULTILINE)
PY_BLOCK_RE = re.compile(r"```python\n(.*?)\n```", re.DOTALL | re.IGNORECASE)


@dataclass
class AuditRecord:
    path: str
    category: str
    title: str
    quality: str
    findings: list[str] = field(default_factory=list)


def normalize(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def related_targets(text: str) -> list[str]:
    targets: list[str] = []
    for left, right in RELATED_RE.findall(text):
        targets.append(left or right)
    return targets


def stale_version(fm: dict, text: str) -> bool:
    version = fm.get("version")
    if not isinstance(version, str) or version not in {"v1", "v2", "v3"}:
        return False
    changelog = text.split("## Changelog", 1)[1] if "## Changelog" in text else ""
    versions = {int(v) for v in re.findall(r"\bv([123])\b", changelog)}
    return bool(versions and max(versions) > int(version[1:]))


def python_syntax_errors(text: str) -> list[str]:
    errors: list[str] = []
    for index, block in enumerate(PY_BLOCK_RE.findall(text), start=1):
        try:
            ast.parse(block)
        except SyntaxError as exc:
            errors.append(f"python example {index}: line {exc.lineno}: {exc.msg}")
    return errors


def audit_skill_files(paths: list[Path]) -> list[AuditRecord]:
    parsed: list[tuple[Path, dict, str, str]] = []
    title_counts: Counter[str] = Counter()
    description_counts: Counter[str] = Counter()

    for path in paths:
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        title = fm.get("title") if isinstance(fm.get("title"), str) else path.stem.replace("-", " ").title()
        description = _description_value(fm, text)
        parsed.append((path, fm, text, title))
        title_counts[normalize(title)] += 1
        if description:
            description_counts[normalize(description)] += 1

    known_paths = {path.name for path in paths}
    records: list[AuditRecord] = []
    for path, fm, text, title in parsed:
        quality = classify(path).classification
        findings: list[str] = []

        if title_counts[normalize(title)] > 1:
            findings.append("duplicated-title")
        description = _description_value(fm, text)
        if description and description_counts[normalize(description)] > 1:
            findings.append("duplicated-description")
        if stale_version(fm, text):
            findings.append("stale-version")

        for target in related_targets(text):
            target_name = Path(target).name
            if target_name not in known_paths:
                findings.append(f"missing-related:{target}")

        findings.extend(f"broken-python:{detail}" for detail in python_syntax_errors(text))
        if any(item.startswith("missing-related:") or item.startswith("broken-python:") for item in findings):
            findings.append("broken")

        records.append(
            AuditRecord(
                path=str(path.relative_to(REPO_ROOT)),
                category=path.parent.name,
                title=title,
                quality=quality,
                findings=sorted(set(findings)),
            )
        )
    return records


def render_markdown(records: list[AuditRecord]) -> str:
    quality = Counter(r.quality for r in records)
    findings = Counter(f.split(":", 1)[0] for r in records for f in r.findings)
    lines = [
        "# Skill Corpus Integrity Audit",
        "",
        "> Auto-generated by `tools/audit_skill_corpus.py`. This audit is conservative and does not infer freshness or compatibility claims.",
        "",
        "## Summary",
        "",
        f"- Total skills: **{len(records)}**",
        f"- Battle-tested: **{quality['battle_tested']}**",
        f"- Enriched: **{quality['enriched']}**",
        f"- Stub: **{quality['stub']}**",
        f"- Invalid: **{quality['invalid']}**",
        f"- Duplicated titles: **{findings['duplicated-title']}**",
        f"- Duplicated descriptions: **{findings['duplicated-description']}**",
        f"- Stale version declarations: **{findings['stale-version']}**",
        f"- Broken skill records: **{findings['broken']}**",
        f"- Missing related targets: **{findings['missing-related']}**",
        "",
        "## Findings",
        "",
    ]
    problem_records = [r for r in records if r.findings]
    if not problem_records:
        lines.append("No integrity findings detected.")
    else:
        lines.extend(
            f"- `{r.path}` — {', '.join(r.findings)}"
            for r in sorted(problem_records, key=lambda item: item.path)
        )
    lines.extend(["", "## Quality classification", "", "| Quality | Count |", "|---|---:|"])
    for key in ("battle_tested", "enriched", "stub", "invalid"):
        lines.append(f"| {key} | {quality[key]} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", dest="json_path", type=Path, help="Write machine-readable JSON to this path.")
    parser.add_argument("--no-write", action="store_true", help="Print the Markdown report without writing it.")
    args = parser.parse_args()

    records = audit_skill_files(list(iter_skill_files()))
    markdown = render_markdown(records)
    if not args.no_write:
        AUDIT_PATH.write_text(markdown, encoding="utf-8")
    if args.json_path:
        args.json_path.write_text(json.dumps([asdict(r) for r in records], indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
